version: "3.7"

services:

  database:
    image: mysql:5.7  
    container_name: database 
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: bookstore_db
      MYSQL_USER: yasin
      MYSQL_PASSWORD: yasin123
    networks:
      - yasinnet

  myapp:
    image: bookstore-api:latest
    container_name: myapp
    restart: always
    depends_on:
      - database
    ports:
      - "80:80"
    networks:
      - yasinnet

networks:
  yasinnet:
  


